# Site settings
title: "Aryan Padhye"
description: "My website"
baseurl: "" # No subpath, because your site is at the root of the domain
url: "https://aryanpadhye.com" # Full URL of your website

# Directories
source: .
destination: ./_site
collections_dir: .
plugins_dir: _plugins # Plugins directory
layouts_dir: _layouts # Layouts directory
data_dir: _data # Data directory
includes_dir: _includes # Includes directory
sass:
  sass_dir: _sass # Sass directory

# Collections
collections:
  posts:
    output: true

# Handling Reading
safe: false
include:
  - ".htaccess"
exclude:
  - "Gemfile"
  - "Gemfile.lock"
  - "node_modules"
  - "vendor/bundle/"
  - "vendor/cache/"
  - "vendor/gems/"
  - "vendor/ruby/"
keep_files:
  - ".git"
  - ".svn"
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
strict_front_matter: false

# Filtering Content
show_drafts: null
limit_posts: 0
future: false
unpublished: false

# Plugins
whitelist: []
plugins: []

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Serving
detach: false
port: 4000
host: 127.0.0.1
baseurl: "" # Base URL (subpath) for the site, empty if at root
show_dir_listing: false

# Outputting
permalink: date
paginate_path: /page:num
timezone: null

quiet: false
verbose: false
defaults: []

# Liquid settings
liquid:
  error_mode: warn
  strict_filters: false
  strict_variables: false

# Markdown Processors
kramdown:
  auto_ids: true
  entity_output: as_char
  toc_levels: [1, 2, 3, 4, 5, 6]
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  input: GFM
  hard_wrap: false
  footnote_nr: 1
  show_warnings: false

